### ISSUE TITLE
请完善readme/使用文档

### ISSUE THREAD

**Issue by stalkercn** [bigmeow/taro-plugin-environment#1]
app内调用方法是什么？
我试了   import.meta.env.TARO_APP_xxx  和 TARO_APP_xxx 都会报错

**Comment by bigmeow** [comment]
> app内调用方法是什么？ 我试了 import.meta.env.TARO_APP_xxx 和 TARO_APP_xxx 都会报错

```ts
console.log(process.env.TARO_APP_xxx)
```

不知道你为什么会import
